### PR TITLE
GROWTH-3245 Stone cut icons

### PR DESCRIPTION
**Pull request by martynas-b**

### CODE REVIEW

**Comment by gedas-monginas** [comment]
I think you also need to run `yarn run compile` so we get updates to https://github.com/nivers/dibs-vg/blob/master/list.json

**Comment by nameofname** [comment]
@gedas-monginas from the contributing doc : 

- Run the command "yarn build" and create your PR to be merged (don't worry if you forget, it's also run as a pre-publish step).

@martynas-b make sure to merge your changes to gh-pages branch so that the new icons will be included in the display page : 
beautifulcode.1stdibs.com/dibs-vg/

**Comment by hellatan** [comment]
> @martynas-b make sure to merge your changes to gh-pages branch so that the new icons will be included in the display page 

@nameofname shouldn't that be done post-merge? and then the `master` branch is the only thing that needs to be merged to `gh-pages`?

**Comment by nameofname** [comment]
@hellatan yeah it should be a post-merge step.

**Comment by gedas-monginas** [comment]
published `dibs-vg@1.50.0`

**Pull request merged**
