### PR TITLE
GOODS-6577 Add circle-erase svg

### PR DESCRIPTION
**Pull request by aahill50**
Adding one more svg for reason codes

### CODE REVIEW

**Comment by hellatan** [comment]
@aahill50 can you generate the other compiled assets so the icon page can is generated with this new icon?

**Comment by aahill50** [comment]
@hellatan done

**Comment by hellatan** [comment]
⬇️ 〰️ tasks, please @aahill50

**Comment by aahill50** [comment]
@nameofname pointed out last time that I don't have permission to publish to the public repo, so what exactly should I be doing here? Should I still publish to sinopia?

**Comment by hellatan** [comment]
ah damn...forgot about that. But i think you need to publish as the 1stdibs account.

**Comment by nameofname** [comment]
@aahill50 I published minor version 1.39

**Comment by aahill50** [comment]
thanks

**Pull request merged**
