### PR TITLE
feat: TRADE-2603 added icon for trade sourcing

### PR DESCRIPTION
**Pull request by hellatan**
thoughts on a different name for this icon? Open to suggestions...

screen shot 2018-07-24 at 4 24 57 pm

### CODE REVIEW

**Comment by moriko** [comment]
`chair-search`? 😆
`chair` -  well as the it's the main object in the svg
`search` - as this magnifying glass is used for the search icon 😏

**Comment by hellatan** [comment]
What about just `sourcing`? That's what the context of the icon is. Do we want to be super literal with this?

**Comment by hellatan** [comment]
@moriko i spoke to design and they said `sourcing` was fine since this is what the icon is going to be initially used. I think in general this is broad enough of a name as well rather than getting too literal with it.

**Comment by hellatan** [comment]
also, `sourcing` is the equivalent of `search` just to be clear

**Pull request merged**
