### PR TITLE
feat: TRADE-2176 added loudspeaker svg

### PR DESCRIPTION
**Pull request by jdk243**
https://1stdibs.atlassian.net/browse/TRADE-2176

### CODE REVIEW

**Comment by moriko** [comment]
Can we name it `loud-speaker`? 😄

**Comment by jdk243** [comment]
@moriko haha, yeah I was debating that, will update

**Comment by hellatan** [comment]
that's not a loudspeaker. it's a megaphone.

**Comment by hellatan** [comment]
google "loudspeaker": https://www.google.com/search?q=loudspeaker&oq=loudspeaker&aqs=chrome.0.0j69i61j69i60j0l3.3056j0j9&sourceid=chrome&ie=UTF-8

google "megaphone": https://www.google.com/search?q=megaphone&oq=megaphone&aqs=chrome..69i57j0l5.1039j0j9&sourceid=chrome&ie=UTF-8

**Comment by hellatan** [comment]
and it would just be "megaphone"

**Pull request merged**
