### PR TITLE
fix: format svgs, added <title> for logo

### PR DESCRIPTION
**Pull request by hellatan**

### CODE REVIEW

**Comment by gedas-monginas** [comment]
so if `title` attribute wasn't doing anything maybe we don't need it at all? :)

**Comment by hellatan** [comment]
i'm ok with leaving it out 😄

**Comment by hellatan** [comment]
the change is in here. I'm going to merge as-is.

**Comment by hellatan** [comment]
these changes can get picked up with whoever bumps this package next

**Pull request merged**
