### PR TITLE
TRADE-860 add on-hold & more-dots svgs

### PR DESCRIPTION
**Pull request by nitruxa**
screenshot 2017-11-28 14 48 35
screenshot 2017-11-28 14 48 43

### CODE REVIEW

**Comment by gedas-monginas** [comment]
```
✨  Done in 7.28s.
+ dibs-vg@1.57.0
```

**Comment by hellatan** [comment]
this shouldn't have been merged b/c a svg can't be localized when it has english copy in it.

**Comment by hellatan** [comment]
you should back out this SVG, actually and have design figure something else out for "hold" or accomplish the "hold" via css/html instead

**Comment by nitruxa** [comment]
@hellatan I've pointed it out in ticket, will ping them once again.

**Pull request merged**
