### PR TITLE
feat: FINDING-13172 SVG optimization

### PR DESCRIPTION
**Pull request by moriko**

### CODE REVIEW

**Comment by moriko** [comment]
Also tried the `mergePaths` but as wasn't in love what it have done to visa icon decided to not use that at the moment. Unless we would create list for icons that should not be svgo'd 🤷‍♀️ 

The visa `(r)` blobed 😒 but maybe it's not a big deal but wouldn't want branded icons change their look in any way.

before | after
------ | ------
screenshot 2018-10-11 15 11 58 | screenshot 2018-10-11 15 10 07

**Comment by hellatan** [comment]
@moriko i think what you have now is fine

**Comment by hellatan** [comment]
@moriko @nameofname @creatyvtype i'm going to make this a patch bump since it's really just a clean up task. Thoughts?

**Comment by moriko** [comment]
Yeah this should go out as a patch 🙇‍♀️

**Comment by hellatan** [comment]
published `dibs-vg@1.78.1`

**Pull request merged**
