### PR TITLE
fix logo box so its not square

### PR DESCRIPTION
**Pull request by walfly**
The old box was square which made styling overly complex

### CODE REVIEW

**Comment by nameofname** [comment]
@hellatan, question 👍 

Walker is updating this so that the bounding box of the logo SVG is not a square. The problem with that is all the other SVGs are in square bounding boxes so that it's easier to tell what dimensions they will be. 

How do you think this should work? Should they all be in squares? Or should the bounding box be the smallest rectangle that fist the SVG?

**Comment by walfly** [comment]
What if instead of making all the svgs square, we just had a prebuilt
square wrapper component available in this library?

**Comment by nameofname** [comment]
@walfly I like the idea. In the mean time we can go ahead and un-squarify the logos. Please run the  command : 
```
npm run prepublish
```
to generate the dist files.

**Comment by walfly** [comment]
@nameofname pushed

**Comment by walfly** [comment]
@nameofname should we be tracking those files?

**Comment by nameofname** [comment]
@walfly you mean the compiled sample pages? I guess it would be ok not to track. Not sure how I would make that work with the sample page and not too motivated to change that atm. 

Thanks for doing that, I will publish this.

**Comment by hellatan** [comment]
Breaking change?

Cc @gedas-monginas

**Comment by gedas-monginas** [comment]
@hellatan probably not , .com doesn't use it yet, so not gonna break anything for us.

**Comment by gedas-monginas** [comment]
@nameofname @walfly you guys want to publish this?

**Comment by walfly** [comment]
@gedas-monginas I believe it is. @nameofname  did you push the tag?

**Comment by walfly** [comment]
@gedas-monginas v1.8.0 contains this change

**Comment by gedas-monginas** [comment]
👍 ty

**Comment by hellatan** [comment]
@walfly @nameofname can someone please push the following tags up to to github: 1.7.1, 1.8.0? The latest tag on github is 1.7.0.

**Comment by nameofname** [comment]
@hellatan I pushed my tags up which included 1.8.0 but does not include 1.7.1. @walfly I'm guessing that's you, can you confirm?

**Comment by hellatan** [comment]
someone pushed up 1.7.1. I see both now. thanks!

**Pull request merged**
